name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y cmake g++ build-essential curl unzip

      - name: Setup test framework
        run: |
          curl -L -o dywoqtest.zip https://github.com/dywoq/tests/releases/download/v1.1.0/dywoqtest-1.1.0.zip
          unzip dywoqtest.zip -d dywoqtest
          sudo cp -r dywoqtest/include/* /usr/include/
          rm -rf dywoqtest dywoqtest.zip

      - name: Build
        run: |
          cmake . -B build
          cmake --build build

      - name: Tests
        run: |
          cd build/lib
          ./dywoqstl_lib_tests

          cd ../runtime
          ./dywoqstl_runtime_tests
